---
title: Puntos de inflexión
lang: es
format:
   html:
    toc: true
    html-math-method: mathjax
    #page-layout: full
    include-in-header: includes-header.html
    # jupyter: python3
---

::: {.callout-note title="Definición"}
Si $f''(a)=0$ y  $f'''(a)\ne 0,$ decimos que  $f$ tiene un punto de inflexión en $a.$  Esto quiere decir que en dicho punto la función pasa de ser cóncava a convexa o al revés. 
:::

Si $f''(a)=0$ y  $f'''(a)\ne 0,$ decimos que  $f$ tiene un punto de inflexión en $a.$  Esto quiere decir que en dicho punto la función pasa de ser cóncava a convexa o al revés. 

Seguimos con la función $f(x)=2x^3-3x^2-2x+1.$ Como $f''(x)=12x-6$ tenemos que $12x-6=0,$ o lo que es lo mismo, $x=\frac{1}{2}.$  Ya tenemos nuestro candidato a punto de inflexión.
$x=\tfrac{1}{2}$. Ya tenemos nuestro candidato a punto de inflexión. Ahora calculamos la derivada tercera: $f'''(x)=12,$ con lo que 
$f'''(1/2)=12>0.$ Por tanto, tenemos un punto de inflexión en $x=\frac{1}{2}.$ Vamos a calcular ahora si pasa de cóncava a convexa, o viceversa. Para ello, evaluamos $f''$ en puntos a ambos lados de $x=1/2.$

$f''(0) = -6 < 0$, por lo que la función antes de $\frac{1}{2}$ es cóncava.
$f''(1) = 6 > 0$, por lo que la función después de $\frac{1}{2}$ es convexa.



::: {.callout-note title="Ejemplo"}
En $-1$ la función tiene un punto de inflexión, ya que cambia de convexa a cóncava.
:::

```{python}
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-2, 2, 400)
y = 2*x**3-3*x**2+1

plt.plot(x, y)
plt.title("f(x) = 2x^3-3x^2+1")
plt.xlabel("x")
plt.ylabel("f(x)")
plt.grid(True)
plt.show()
```


    




::: {.sage}
<script type="text/x-sage">
x = var('x')
f = 2*x^3 - 3*x^2 - 2*x + 1

plot(f, (x, -2, 2), gridlines=True, title="f(x) = 2x^3 - 3x^2 - 2x + 1")

</script>
:::